name: Go
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test-and-scan:
    name: Test and SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      
      - name: Download dependencies
        run: go mod download

      - name: Run tests with coverage
        run: |
          echo "Running tests with coverage..."
          go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
          echo "Test run completed"
      
      # 🔍 DEBUG SECTION - Remove after fixing
      - name: Debug coverage file
        run: |
          echo "=== Coverage File Debug ==="
          if [ -f coverage.out ]; then
            echo "✅ Coverage file exists"
            echo "File size: $(wc -l coverage.out)"
            echo "First 15 lines:"
            head -15 coverage.out
            echo "Last 5 lines:"
            tail -5 coverage.out
            echo "=== Coverage Summary ==="
            go tool cover -func=coverage.out | tail -1
          else
            echo "❌ Coverage file NOT found!"
            echo "Files in current directory:"
            ls -la
            exit 1
          fi

      # 🔧 FIX ATTEMPT 1: Clean up coverage paths
      - name: Fix coverage file paths
        run: |
          if [ -f coverage.out ]; then
            echo "Original coverage file:"
            head -5 coverage.out
            # Remove module prefix to make paths relative
            sed -i 's|github.com/basebandit/kai/||g' coverage.out
            echo "Modified coverage file:"
            head -5 coverage.out
          fi

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build
        run: go build -v ./cmd/kai