name: goreleaser

on: 
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly' or a semver version like 'v2.0.0'
          version: "~> v2"
          args: release --clean
          workdir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}